# -*- coding: utf-8 -*-
"""EXERCÍCIOS 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qc4AZNtMIRpx9_DBY-DaxuFjTmbqZ2U4

# EXERCÍCIO 1
"""

idade = int(input('Insira a idade do usuário:'))

print(idade)

if idade < 0:
  print('Idade inválida')
else:
  if idade <= 12:
    print('Criança')
  else:
    if idade <= 17:
      print('Adolescente')
    else:
        print('Adulto')

"""# EXERCÍCIO 2"""

m1 = float(input('Insira a nota M1:'))
m2 = float(input('Insira a nota M2:'))
m3 = float(input('Insira a nota M3:'))

media = (m1 + m2 + m3) / 3

print(media)

if media <= 4.0:
  print('Reprovado')
elif media <= 6.0:
    print('Pegou exame')
    nota_exame = float(input('Insira a nota do exame:'))
    if nota_exame >= 6.0:
      print('Aprovado')
    else:
      print('Reprovado')
else:
    print('Aprovado')