# -*- coding: utf-8 -*-
"""EXERCÍCIOS 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kb6cOE90GnZFiFjmqBUrBzrGMW8Jx2tr

# LISTA
"""

lista = []
for i in range (0, 5):
  numero = int(input('Insira um número inteiro: '))
  lista.append(numero)
print(lista)

soma = 0
for i in range(len(lista)):
  soma += lista[i]

print('A soma dos valores digitados é: ', soma)

import numpy as np
np.array(lista).sum()

"""# DICIONÁRIO"""

coleta = {}
for i in range(1 , 4):
  nome = input(f'Insira o nome do {i}o aluno: ')
  nota = float(input(f'Insira a nota do {i}o aluno: '))
  coleta[nome] = nota

print(coleta)

soma = 0
for nota in coleta.values():
  soma += nota

media = soma/3

print('A média das notas é: ', media)

"""# Matriz"""

matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])

soma = 0

for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    soma += matriz[i][j]

print('A soma dos elementos da matriz é: ', soma)