# -*- coding: utf-8 -*-
"""EXERCÍCIOS 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0QS_BJz4ypQYiLpKlmgF-eq0JXtqSP6

# EXERCÍCIO 1
"""

#FOR

soma = 0
for i in range(0,5):
  nota = float(input('Insira a nota: '))
  soma += nota

media = soma / 5

print('A media é ', media)

#WHILE

soma = 0
numero = 1
while numero <= 5:
  nota = float(input('Insira a nota: '))
  soma += nota
  numero += 1

media = soma / 5

print('A média é ', media)

"""# EXERCÍCIO 2"""

#FOR

for i in range(1, 11):
  multiplicacao = 3 * i
  print('3 x ', i, ' = ', multiplicacao)

#WHILE

numero = 1
while numero < 11:
  multiplicacao = 3 * numero
  print('3 x ', numero, ' = ', multiplicacao)
  numero += 1