# -*- coding: utf-8 -*-
"""EXERCÍCIOS 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11d0zxXfMqPleeKvzIp8CTmNB0G0q3u3w

# EXERCÍCIO 1
"""

def ler_temp():
  c = float(input('Insira o valor da temperatura em graus Celsius: '))
  return c

def c_para_f(c):
  f = (9.0 * c + 160.0)/5.0
  return f

def resultado(f):
  print('A temperatura em Fahrenheit é:', f)

c = ler_temp()
f = c_para_f(c)
resultado(f)

"""# EXERCÍCIO 2"""

def ler_dados():
  tempo_gasto = float(input('Insira o tempo gasto na viagem: '))
  velocidade_media = float(input('Insira a velocidade média durante a viagem: '))
  return tempo_gasto, velocidade_media

def distancia(tempo_gasto, velocidade_media):
  d = tempo_gasto * velocidade_media
  return d

def qtd_litros(d):
  litros_usados = d / 12
  return litros_usados

def imprimir_resultados(tempo_gasto, velocidade_media, d, litros_usados):
  print('Tempo gasto:', tempo_gasto)
  print('Velocidade média:', velocidade_media)
  print('Distância:', d)
  print('Litros usados:', litros_usados)

tempo, velocidade = ler_dados()
d = distancia(tempo, velocidade)
litros = qtd_litros(d)
imprimir_resultados(tempo, velocidade, d, litros)